import os
from pathlib import Path

# pytest_plugins is generated by `project_gen generate` into this file


def pytest_configure(config):
    """Ensure consistent working directory for pytest for allure and coverage outputs"""
    current_dir = Path.cwd()
    if 'tests' in str(current_dir):
        project_root = str(current_dir).split('/test')[0]
        os.chdir(project_root)
        print(f'Changed working directory to: {project_root}')
