import os
from pathlib import Path
import pytest

# pytest_plugins is generated by `project_gen generate` into this file


def pytest_configure(config):
    """Ensure consistent working directory for pytest for allure and coverage outputs"""
    current_dir = Path.cwd()
    if 'tests' in str(current_dir):
        project_root = str(current_dir).split('/test')[0]
        os.chdir(project_root)
        print(f'Changed working directory to: {project_root}')


@pytest.fixture(autouse=True, scope="function")
def data_healer(request):
    """
    Auto-injected fixture available to every test.

    After the API call the test passes the response to data_healer():
      - No snapshot yet  → saves initial expected_result, test passes
      - Snapshot exists  → runs assertions; if data changed, proposes
                           an interactive update and re-raises the failure
    """
    test_file = Path(str(request.fspath))

    # tests/svc/api_group/test_folder/test_x.py → expected_result/svc/api_group/test_folder/
    project_root = test_file.parent
    while project_root.name != "tests" and project_root != project_root.parent:
        project_root = project_root.parent
    project_root = project_root.parent  # one level above tests/

    try:
        rel_parts = test_file.relative_to(project_root / "tests").parts[:-1]
        snapshot_dir = project_root / "expected_result" / Path(*rel_parts)
    except ValueError:
        snapshot_dir = test_file.parent / "expected_result"

    def heal(response) -> None:
        from checkers.utils import check_response
        check_response(response, snapshot_dir)

    return heal
